name: test

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: |
        brew update
        brew tap yuizho/homebrew-pomors
        brew install pomors
    - name: run pomors with --version
      run: pomors --version
